### PR TITLE
Add AssumeRoleWithWebIdentity

### PR DESCRIPTION
**Pull request by rafaelgaspar**
This adds support for AssumeRoleWithWebIdentity according to AWS Documentation at: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html

### CODE REVIEW

**Comment by tecnobrat** [comment]
I'm unsure what the merging policy is here, but looking at the code and tests, this looks really good to me.

We're looking for this feature to handle EKS roles.

**Comment by maur1th** [comment]
We need this as well. What is blocking this PR?

**Comment by benwilson512** [comment]
> What is blocking this PR?

https://github.com/ex-aws/ex_aws_sts/issues/1

**Comment by rafaelgaspar** [comment]
Just as an update, I'm waiting for reviews on this and some confirmation that the project is not dead, since it's been more than a month now.

After that it would still be missing an AuthCache Adapter to be able to use it as an authentication mechanism for `ex_aws`, that I will work on as soon I get a confirmation that this project is not dead.

**Comment by benwilson512** [comment]
@rafaelgaspar as the original project author, I'm trying to say that this project needs a maintainer. ExAws has become federated since it was impossible for one person to handle all of the libraries. If you'd like to be the maintainer we can discuss that.

**Comment by dcaixinha** [comment]
Hey, I'm currently needing this as well at work. Given there are people volunteering to maintain on #1, can this get unblocked @benwilson512? :pray: after this gets merged we can open a PR to add the new auth adapter :raised_hands:

**Pull request merged**
